name: VST3 Build Windows

on:
  push:
    branches: [ main, master ]

jobs:
  build_vst3:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Clone JUCE
      run: git clone --depth 1 https://github.com/juce-framework/JUCE.git

    - name: Configure CMake
      run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build VST3
      run: cmake --build build --config Release --target NovaMB_VST3 --verbose -j 4

    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaMB-VST3-Windows
        path: build/NovaMB_artefacts/Release/VST3/NovaMB.vst3
